
name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Clone repo
      - uses: actions/setup-node@v1
        name: Set up node
      - run: npm ci
        name: Install dependencies
      - run: npm run build
        name: Build